// <auto-generated />
using System;
using EtherpunkBlazorWasm.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtherpunkBlazorWasm.Server.Data.Migrations
{
    [DbContext(typeof(EpunkDbContext))]
    partial class EpunkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a228fa83-e5b6-4d1d-9636-55228302b22f"),
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e39dfd1f-85b8-4586-8a98-037611b60558"),
                            CreatedOn = new DateTime(2022, 10, 17, 1, 40, 43, 908, DateTimeKind.Utc).AddTicks(3242),
                            Email = "admin@admin.com",
                            PasswordHash = "$2b$12$k87L/MF28Q673VKh8/cPi.pNe6atmnYcCQXfH80DwODOUtvUgB1NK"
                        },
                        new
                        {
                            Id = new Guid("dc09e4be-9631-4adf-b65e-6a396859b946"),
                            CreatedOn = new DateTime(2022, 10, 17, 1, 40, 44, 170, DateTimeKind.Utc).AddTicks(4167),
                            Email = "regularuser1@user.com",
                            PasswordHash = "$2b$12$k87L/MF28Q673VKh8/cPi.pNe6atmnYcCQXfH80DwODOUtvUgB1NK"
                        },
                        new
                        {
                            Id = new Guid("4e375925-a166-4924-8289-c80718f83c29"),
                            CreatedOn = new DateTime(2022, 10, 17, 1, 40, 44, 425, DateTimeKind.Utc).AddTicks(1649),
                            Email = "regularuser2@user.com",
                            PasswordHash = "$2b$12$k87L/MF28Q673VKh8/cPi.pNe6atmnYcCQXfH80DwODOUtvUgB1NK"
                        });
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("a228fa83-e5b6-4d1d-9636-55228302b22f"),
                            UserId = new Guid("e39dfd1f-85b8-4586-8a98-037611b60558")
                        });
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppUserRole", b =>
                {
                    b.HasOne("EtherpunkBlazorWasm.Server.Data.Entities.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtherpunkBlazorWasm.Server.Data.Entities.AppUser", "User")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppUser", b =>
                {
                    b.Navigation("AppUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
