// <auto-generated />
using System;
using EtherpunkBlazorWasm.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtherpunkBlazorWasm.Server.Data.Migrations
{
    [DbContext(typeof(EpunkDbContext))]
    partial class EpunkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("AppRoleAppUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("TEXT");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppRoleAppUser");
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f37e0a2-90a5-4415-bf47-c27a6f2837ac"),
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("427863b6-a80c-426a-8643-52db48bbd85e"),
                            CreatedOn = new DateTime(2022, 10, 8, 15, 6, 32, 856, DateTimeKind.Utc).AddTicks(5553),
                            Email = "admin@admin.com",
                            PasswordHash = "UAJrWMszfBmTFvmv395EJw=="
                        });
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("7f37e0a2-90a5-4415-bf47-c27a6f2837ac"),
                            UserId = new Guid("427863b6-a80c-426a-8643-52db48bbd85e")
                        });
                });

            modelBuilder.Entity("AppRoleAppUser", b =>
                {
                    b.HasOne("EtherpunkBlazorWasm.Server.Data.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtherpunkBlazorWasm.Server.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EtherpunkBlazorWasm.Server.Data.Entities.AppUserRole", b =>
                {
                    b.HasOne("EtherpunkBlazorWasm.Server.Data.Entities.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtherpunkBlazorWasm.Server.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
